version: "3.9"
services:
  postgres-auth:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth-db:/var/lib/postgresql/data

  postgres-order:
    image: postgres:15
    environment:
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order-db:/var/lib/postgresql/data

  auth-service:
    build: ./auth-service
    depends_on:
      - postgres-auth
    environment:
      DB_HOST: postgres-auth
      DB_PORT: 5432
      DB_USER: auth_user
      DB_PASS: auth_pass
      DB_NAME: auth_db
      JWT_SECRET: mysecret
    ports:
      - "8081:8081"

  upload-service:
    build: ./upload-service
    ports:
      - "8082:8082"

  ghibli-service:
    build: ./ghibli-service
    ports:
      - "8083:8083"

  order-service:
    build: ./order-service
    depends_on:
      - postgres-order
    environment:
      DB_HOST: postgres-order
      DB_PORT: 5432
      DB_USER: order_user
      DB_PASS: order_pass
      DB_NAME: order_db
    ports:
      - "8084:8084"

  gateway:
    build: ./gateway
    depends_on:
      - auth-service
      - upload-service
      - ghibli-service
      - order-service
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: "http://auth-service:8081"
      UPLOAD_SERVICE_URL: "http://upload-service:8082"
      GHIBLI_SERVICE_URL: "http://ghibli-service:8083"
      ORDER_SERVICE_URL: "http://order-service:8084"
      JWT_SECRET: "mysecret"

  frontend:
    build: ./frontend
    depends_on:
      - gateway
    ports:
      - "3000:3000"

volumes:
  auth-db:
  order-db:
